import toml
from decouple import config

DISCORD_TOKEN = config("DISCORD_TOKEN")
DISCORD_INVITE_LINK_ID = config("DISCORD_INVITE_LINK_ID")
DISCORD_CHANNELS_FROM = config("DISCORD_CHANNELS_FROM")
TELEGRAM_TOKEN = config("TELEGRAM_TOKEN")
TELEGRAM_GROUPS_TO = config("TELEGRAM_GROUPS_TO")
